### ISSUE TITLE
Bug When Using Magic Missile 

### ISSUE THREAD

**Issue by xNewbieeer** [CammiePone/Arcanus#16]
Hello . Recently , I play with my friends on a server . We add origin and arcanus mod in the server. At first all of the thing working fine and very good to play , but when I choose a origin that allow me to walk through the wall some bug happen . If I use magic missile in wall , the server will say "Internal Server Error" and I cannot join the server again unless you delete the players data.
![photo_2021-10-03_17-42-25](https://user-images.githubusercontent.com/91825652/135748225-b5b78ddf-0802-4658-9cf4-7926447ef241.jpg)

**Comment by CammiePone** [comment]
Origins has a known issue that causes this bug. If it persists after it's fixed (which should be soon), or persists after removing Origins, then it is time for me to suffer because this error has been the bane of my existence for the past few weeks.

Idk if it's Arcanus or some other mod at this point.
