### ISSUE TITLE
Use custom namespace for brigadier arguments

### ISSUE THREAD

**Issue by Xernium** [CammiePone/Arcanus#60]
https://github.com/CammiePone/Arcanus/blob/40611ebaf057b1bfa383e473d9be3f4759dd382e/src/main/java/dev/cammiescorner/arcanus/core/registry/ModCommands.java#L36 registers your argument type spells in the `minecraft:` namespace.    
You should register it under `arcanus:spells` instead of using the reserved minecraft namespace.     
Using the reserved namespace (brigadier: or minecraft:) makes it incompatible with networks running fabric servers (under Velocity for example)

**Comment by CammiePone** [comment]
I only support latest, and 1.19 forces you to use an identifier, and I always use the arcanus namespace when an identifier is required.

**Comment by Xernium** [comment]
…. But you are still using minecraft:spells in 1.19 and newer? True it uses an ID now for the network, but that still breaks compatibility with the crossstitch mod which still identifies by namespace on 1.19; This transaction happens on the server/client only now; for you it is won’t change anything but for us it would still fix compatibility if you used your own namespace.    
Reference:
https://github.com/VelocityPowered/CrossStitch/blob/master/src/main/java/com/velocitypowered/crossstitch/mixin/command/CommandTreeSerializationMixin.java#L33

**Comment by CammiePone** [comment]
the line you linked on the 1.18 branch is this on the 1.19 branch. it uses the Arcanus namespace, and as I said, i dont update old versions. I dont get paid to, and I make mods for my own enjoyment. no offense, but if it breaks, it breaks. just tell people to not use my mods with your thing unless they're on 1.19 or higher

same line on the 1.19 branch:
https://github.com/CammiePone/Arcanus/blob/1.19-dev/src/main/java/dev/cammiescorner/arcanus/core/registry/ModCommands.java#L36

and if you've confirmed it still doesnt work on 1.19, then idk what more I can say because that's most likely not my fault. only thing I could do it change the command itself to /arcanus_spells which im not keen on

**Comment by CammiePone** [comment]
I should clarify btw, I would gladly fix it if 1.18 was current, but since it's not, i dont have any reason to go back and fix the bug. if I was being paid to make mods, sure, then I'd do it, but this is a hobby for me. I have no obligation to support versions I dont want to

**Comment by Xernium** [comment]
My apologies, the Git desktop client did a number on me again and displayed me the caches for the 1.18 branch when I selected the 1.19 branch. I see now what you mean. Thanks for being so understanding.

**Comment by CammiePone** [comment]
nw, I wouldnt put it past Minecraft to muck it up either way, and I didnt know what you did to check the 1.19 version
