### ISSUE TITLE
Solar Strike on a MP Server using the DarkRPG modpack

### ISSUE THREAD

**Issue by Wrexial** [CammiePone/Arcanus#76]
Is there a known bug with the Solar Strike spell which seems to persist for a long time even after the server restarts/shuts down?

**Comment by BryanP88** [comment]
I am having the same issue, this is the big blue beam right? It just keeps raining down and killing people. Until the bug is fixed I just went into the json file and set the enable on it to false so no one can use it. 

Edit: Whelp... that's didn't help. There is permanent blue beam moving around randomly on the server and killing everyone.

**Comment by Wrexial** [comment]
Yes exactly that's the one, and we have no idea how we can manually shut the strike instance down

**Comment by Wrexial** [comment]
Edit: We've just realised it happens even if you respawn next to the strike location

**Comment by BryanP88** [comment]
@Wrexial 

You can delete it when it appears by running this command /kill @e[type=arcanus:solar_strike]
It's fixed on our server now.

**Comment by Wrexial** [comment]
Great thanks!
